version: '3.8'
services: 
  postgres.dev:
    image: postgres:12
    logging:
        driver: none
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: passwordispassword
      POSTGRES_USER: example_user
      POSTGRES_DB: example_db
    volumes:
      - example.postgres:/var/lib/postgresql/data

volumes:
  example.postgres: